### ISSUE TITLE
Package restore

### ISSUE THREAD

**Issue by scottcowan** [julianghionoiu/tdl-runner-csharp#3]
Hey @julianghionoiu great work on this.

It would be good to have package restore turned on so you don't have to do it manually

https://stackoverflow.com/questions/27895504/how-do-i-enable-nuget-package-restore-in-visual-studio

**Comment by julianghionoiu** [comment]
Hey @scottcowan, thanks for reaching out!

So this option is to enable `nuget` to download incomplete packages. Right?
Here is how my VS config looks like: https://prnt.sc/hgfgi4

**Comment by scottcowan** [comment]
ya that should do it

**Comment by scottcowan** [comment]
my bad I deleted my packages and built the solution and it restores the packages fine. 

cheers Julian :beers:

**Comment by julianghionoiu** [comment]
Would you like to get a challenge link to try the entire experience?
